###########################################################
#################### RuboCop Capybara #####################
###########################################################

# You can find all configuration options for rubocop-capybara here: https://docs.rubocop.org/rubocop-capybara/

Capybara/ClickLinkOrButtonStyle: # new in 2.19
  Enabled: true

Capybara/MatchStyle: # new in 2.17
  Enabled: true

Capybara/NegationMatcher: # new in 2.14
  Enabled: true

Capybara/RedundantWithinFind: # new in 2.20
  Enabled: true

Capybara/SpecificActions: # new in 2.14
  Enabled: true

Capybara/SpecificFinders: # new in 2.13
  Enabled: true

Capybara/SpecificMatcher: # new in 2.12
  Enabled: true

Capybara/RSpec/HaveSelector: # new in 2.19
  Enabled: true

Capybara/RSpec/PredicateMatcher: # new in 2.19
  Enabled: true
